/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class TransformerAppTest {
    @Test void testBlackAndWhite() throws IOException {
        TransformerApp classUnderTest = new TransformerApp();

        String[] args = {
                "src/main/resources/baldy-8bit.bmp",
                "src/main/resources/test2.bmp",
                "tbw"
            };

        TransformerApp.main(args);

        File output = new File("src/main/resources/test2.bmp");
        BufferedImage bfo = ImageIO.read(output);

        File source = new File("src/test/resources/blackwhite.bmp");
        BufferedImage bfs = ImageIO.read(source);

        int height = bfo.getHeight();
        int width = bfo.getWidth();

        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                assertEquals(bfo.getRGB(x, y), bfs.getRGB(x, y));
            }
        }
    }@Test void testIncreaseBrightness() throws IOException {
        TransformerApp classUnderTest = new TransformerApp();

        String[] args = {
                "src/main/resources/baldy-8bit.bmp",
                "src/main/resources/test1.bmp",
                "tib"
            };

        TransformerApp.main(args);

        File output = new File("src/main/resources/test1.bmp");
        BufferedImage bfo = ImageIO.read(output);

        File source = new File("src/test/resources/brightness.bmp");
        BufferedImage bfs = ImageIO.read(source);

        int height = bfo.getHeight();
        int width = bfo.getWidth();

        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                assertEquals(bfo.getRGB(x, y), bfs.getRGB(x, y));
            }
        }
    }
}
